# Generated by Django 2.0.5 on 2018-05-19 14:38

from django.db import migrations, models
import django.db.models.deletion
import votes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=2000)),
                ('nest_comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='votes.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=votes.models.Proposal.generate_filename)),
                ('description', models.CharField(max_length=5000)),
                ('close_date', models.DateField(blank=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Phase')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Proposal'),
        ),
    ]
