# Generated by Django 2.0.5 on 2018-05-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20180519_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproposalphasevote',
            name='salt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userproposalphasevote',
            name='unique_id',
            field=models.CharField(max_length=200),
        ),
    ]
