# Generated by Django 2.0.5 on 2018-05-22 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_auto_20180522_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalPhaseVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.BooleanField(default=True)),
                ('unique_id', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('salt', models.CharField(max_length=100)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Phase')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Proposal')),
            ],
        ),
        migrations.RemoveField(
            model_name='userproposalphasevote',
            name='option',
        ),
        migrations.RemoveField(
            model_name='userproposalphasevote',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='userproposalphasevote',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='userproposalphasevote',
            name='unique_id',
        ),
    ]
