# Generated by Django 2.0.5 on 2018-05-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0009_auto_20180528_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalphasevote',
            name='user_pw',
            field=models.CharField(max_length=200),
        ),
    ]
