# Generated by Django 2.0.5 on 2018-05-28 21:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0011_auto_20180528_2342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproposalphasevote',
            unique_together={('phase', 'proposal', 'user')},
        ),
    ]
