# Generated by Django 2.0.5 on 2018-05-28 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0012_auto_20180528_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalphasevote',
            old_name='unique_id',
            new_name='hash',
        ),
    ]
