# Generated by Django 2.0.5 on 2018-06-02 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0013_auto_20180529_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='close_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 6, 7)),
        ),
    ]
