# Generated by Django 2.0.5 on 2018-06-09 14:38

from django.db import migrations, models
import django.db.models.deletion
import votes.models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0015_auto_20180603_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='close_date',
            field=models.DateField(default=votes.models.Proposal.default_close_date),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='phase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='votes.Phase'),
        ),
    ]
